### ISSUE TITLE
Way of Building Dictionary is incorrect

### ISSUE THREAD

**Issue by b0noI** [b0noI/aif-cli#8]
Current CLI builds dictionary without splitting text to sentences. This generates artifacts id dictionary like:

developer., developer, developer,

this should be one token: developer

correct way of generating Dict could be found here: https://github.com/b0noI/AIF2/blob/038a7bd8f6206cd873792456cb64eb9003c950a6/src/test/integration/java/io/aif/language/word/dict/DictBuilderTest.java#L44

**Comment by xeenhl** [comment]
fixed in https://github.com/b0noI/aif-cli/commit/c3a0d39977dfa844d1f9bb6e6a12c7e37f38a40a commit
